### ISSUE TITLE
Error on Hello World Contract installation

### ISSUE THREAD

**Issue by zmanian** [eris-ltd/hello-world-dapp#1]
`go version`
`go version go1.4 linux/amd64`

`epm -p helloworld.pdx -diff -log 2`

```
2015/01/13 19:25:38 [EPM-CLI] There was no test found for package-definition helloworld. Deploying without test ...
compiling remotely...
failed to unmarshal json: cannot unmarshal string into Go value of type [][]uint8
diff: TEST

2015/01/13 19:25:52 Error compiling /home/zaki/.decerver/dapps/helloworld/contracts/test.lll: json: cannot unmarshal string into Go value of type [][]uint8

```

**Comment by dennismckinnon** [comment]
We are investigating and hope to have an solution for you shortly.

**Comment by zmanian** [comment]
Thanks. We have two machines running trusty with the bug and two machines running trusty without it.

**Comment by dennismckinnon** [comment]
That is extremely odd. We suspect it might have to do with the remote compiling server we have running for you. Can you confirm that the following repos are on master branch?

$GOPATH/src/github.com/...

/eris-ltd/thelonious/
/eris-ltd/epm/
/eris-ltd/decerver-interfaces/
/eris-ltd/decerver/

/project-douglas/lllc-server/

That would be helpful to rule out any other possible sources. they should be if you have been following the tutorial but best to check.

**Comment by ebuchman** [comment]
My bad! I recently gave the server an overhaul and accidentally ran the develop version. Should be good to go now. Though I can't possibly understand how two of your machines didn't fail - it was totally on our end!

Side note: why a server? It's for the smart contract languages - to avoid you having to install the c++ compiler, we default to pinging our compiler server. The old master version only serves LLL, but the new version will serve serpent too. Those changes should be on master (and correspondingly pushed to the server) by the end of the week

**Comment by zmanian** [comment]
Everything is master. 

I get this error when I start the decerver.
20:28:36.066 CRITI       core: Bootstrapping error: Handshake1 failed: could not decode remote version: "proto: handshake_pb.Handshake1: illegal tag 0" core.go:268

**Comment by zmanian** [comment]
Fixed!
