### ISSUE TITLE
Running test behind a corporate proxy (with a domain)

### ISSUE THREAD

**Issue by KoenVingerhoets** [eris-ltd/hello-world-dapp#12]
To run the test behind a corporate proxy (one where the user requires a domain), you have to update two files. You can update these in the folder where you downloaded hello-world-app, the test.sh script copies the data to a hidden folder in /home/eris/

==== hello-world-app/test/Dockerfile. ====
The line with "RUN npm install" needs to be extended with the required data
(1) `--strict-ssl=false`
(2) `--https-proxy=http://[domain]%5C[user]:[pass]@[server]:[port]` (ex: --https-proxy=http://company%5Cmyself:mypassword@proxyserver:8080); do mind the https-proxy, not https_proxy and the url encoded backslash (%5C)
My line: `RUN npm install --strict-ssl=false --https-proxy=http://company%5Cmyself:mypassword@proxyserver:8080`

It is, in my experience, pointless to set npm_global params, use a .npmrc file or whatever. Just update the Dockerfile where you downloaded it.

Imho, this is an issue. While the solution is above, it requires manual work... so not perfect.

==== hello-world-app/test/nightwatch.json ====
The json files alas doesn't support comments (quite a mistake imho). In order to use it behind a proxy, the nightwatch.json needs to be equipped with the proxy details.
In the nightwatch.json configuration file, you should be able to set a proxy parameter in the desiredCapabilities: 
`"chrome" : { 
    "desiredCapabilities": { 
        "browserName": "chrome", 
        "javascriptEnabled": true, 
        "acceptSslCerts": true, 
        "chromeOptions" : { "args" : [ "disable-extensions", "start-maximized" ] }, 
        "proxy": { 
            "proxyType": "manual", 
            "httpProxy": "your_proxy:8080" } 
    }
},`

Keep in mind the proxy details require an escape sequence when dealing with a domain.
Ex: `http://\myDomain\\myUser:myPassword@myProxy:8080`

**Comment by compleatang** [comment]
Thanks for the report. We're happy to help make this as easy as we can, given the divergent environments that folks operate in.
