### ISSUE TITLE
test.sh: ✖  Timed out while waiting for element <//input[@id="filenameAdd"]> to be present for 10000 milliseconds.  - expected "visible" but got: not found

### ISSUE THREAD

**Issue by AronVanAmmers** [eris-ltd/hello-world-dapp#8]
Trying to get a container-based install running on Ubuntu 14.04 per https://docs.erisindustries.com/. Getting the `helloworld` tests to run seemed like a good start.

`docker` and `docker-compose` installed. After several runs of `test.sh` all docker images have been downloaded and the containers seem to be running fine. However the the error below remains. Also, http://localhost:3000/admin/switch/helloworld gives `Error loading dapp: helloworld. No dapp with that name has been registered.`

The only change I made to test.sh is add `sudo` before all calls to `docker-compose`.

Output of `sudo docker ps` (containers seem to be running fine):

```
CONTAINER ID        IMAGE                              COMMAND                CREATED             STATUS              PORTS                                                                                   NAMES
60c359b6542d        helloworld_helloworldread:latest   "/bin/sh -c /home/$u   5 minutes ago       Up About a minute   30304/tcp, 4001/tcp, 4002/udp, 15254/tcp, 3005/tcp, 30303/tcp, 0.0.0.0:3000->3000/tcp   helloworld_helloworldwrite_1
def27afedf16        eris/compilers:latest              "lllc-server"          5 minutes ago       Up 5 minutes        9099/tcp                                                                                helloworld_compilers_1
9ba0fb644b99        eris/erisdb:latest                 "./start.sh"           5 minutes ago       Up 5 minutes        15254/tcp, 15256/tcp, 15255/tcp                                                         helloworld_helloworldmaster_1
c22be5d5ab09        eris/ipfs:latest                   "start.sh"             5 minutes ago       Up About a minute   5001/tcp, 0.0.0.0:4001->4001/tcp, 0.0.0.0:8080->8080/tcp                                helloworld_ipfs_1
b4b7dc971b2b        selenium/node-chrome:latest        "/opt/bin/entry_poin   30 minutes ago      Up 44 seconds       0.0.0.0:5900->5900/tcp                                                                  helloworld_seleniumnode_1
c2bd0f24aafd        selenium/hub:latest                "/opt/bin/entry_poin   30 minutes ago      Up 45 seconds       4444/tcp                                                                                helloworld_seleniumhub_1
49ef7ac0baca        helloworld_helloworldread:latest   "/bin/sh -c /home/$u   30 minutes ago      Up 46 seconds       4002/udp, 15254/tcp, 3005/tcp, 30303/tcp, 30304/tcp, 4001/tcp, 0.0.0.0:3001->3000/tcp   helloworld_helloworldread_1

```

Full output of test.sh: (the lines `sudo: unable to resolve host thewire` can likely be ignored as sudo works just fine)

```
aron@thewire:~/.eris/dapps/helloworld$ ./test.sh
sudo: unable to resolve host thewire
sudo: unable to resolve host thewire
sudo: unable to resolve host thewire
sudo: unable to resolve host thewire
2015/06/04 12:53:43 compiling remotely...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    75  100    75    0     0   4143      0 --:--:-- --:--:-- --:--:--  4411


Hello World Writer's DOUG Contract is at:
0x96373bf178251167fd75c59d5946cb27b06353ba

sudo: unable to resolve host thewire
sudo: unable to resolve host thewire
sudo: unable to resolve host thewire

> @ start /home/node
> nightwatch


[Hello World] Test Suite
========================

Running:  Hello World

✖  Timed out while waiting for element <//input[@id="filenameAdd"]> to be present for 10000 milliseconds.  - expected "visible" but got: not found


TEST FAILURE: 1 assertions failed, 0 passed and 12 skipped.. (14.333s)

npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.38
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! @ start: `nightwatch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'nightwatch'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nightwatch
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/node/npm-debug.log
```

**Comment by compleatang** [comment]
just tried in a perfectly clean VM and cannot reproduce. 

can you try running test_debug.sh which will give you a bit more output so we can see where the problem is?

**Comment by AronVanAmmers** [comment]
Done. At first, piping `test-debug.sh` to a log file showed a memory error (which I might have missed earlier). After increasing the VM mem from 1GB to 2GB that disappeared.

Output here, acquired with `sudo ./test-debug.sh > output.log`:
https://gist.github.com/AronVanAmmers/7482fe7ef724a76cbb01#file-helloworld-test-debug-sh-output

The file seems to miss the last bits vs what I see in the console if running without piping to a file. Let me know if that's a problem; the last lines on my screen seem a repetition to the admin/switch error below.

Something seems off here, not sure if it's important:
https://gist.github.com/AronVanAmmers/7482fe7ef724a76cbb01#file-helloworld-test-debug-sh-output-L771

The admin/switch error is here:
https://gist.github.com/AronVanAmmers/7482fe7ef724a76cbb01#file-helloworld-test-debug-sh-output-L847

**Comment by AronVanAmmers** [comment]
Re-testing with a clean VM here too. The docker version used above was 1.5.0.

**Comment by compleatang** [comment]
This is strange. For some reason the write node isn't getting started.

So the architecture of the HW test is as follows:

* helloworldmaster (creates a blockchain and acts as a peer server... does not deploy the contracts)
* helloworldwrite (acts as decerver node; fetches chain from master; deploys contracts; sets the DApp's root contract; during selenium tests (which are off in the debug script) "writes" to the HW form)
* helloworldread (acts as decerver node; fetches chain from master; deploys contracts (which are ignored); reads the results from the unified chain)

I cannot see why but it looks like you have 2 HWmaster nodes and 2 HWread nodes but no HWwrite node.

**Comment by AronVanAmmers** [comment]
`helloworld` is working correctly after the following actions:
* Remove all docker containers
* Remove all docker images
* Update docker from 1.5.0 to current 1.6.2
* Running `test-debug.sh` again

My guess toward the cause was that I have used this VM before. So either it was old versions of images/containers that were conflicting, or the older Docker version.

Currently it's still downloading the selenium images so the complete test hasn't run, but I'm confident it will as helloworld can now be opened through http://localhost:3000/helloworld as it should.

**Comment by compleatang** [comment]
Super! :fireworks: 

Glad to hear it is working. It could have been old containers which preceded our 0.9 release (some minor details for starting changed with that release). To force docker to get updated images you can just use `docker pull ...` that will ensure you have the latest containers available locally.

**Comment by AronVanAmmers** [comment]
Thanks, will do `docker pull` to force in the future. It seemed to download a lot of images already so I assumed it had the latest.

Tests are now running as expected too. Yay! :+1:

**Comment by compleatang** [comment]
:+1:  (and sorry for the hassles) We use the HW test suite as our full integration test suite after pushing major components so it does download quite a few images.

**Comment by AronVanAmmers** [comment]
You don't say :wink:. Well +-2GB of downloads is not so bad for a developer on broadband. For end users... not so much. But I'm sure that'll be ironed out.

Anyway I think it's great you have this complete testing setup available with a very compact set of commands; when it runs correctly one can be sure the whole stack runs excellent.
