### ISSUE TITLE
test.sh: test for getting file fails (nodes don't communicate?)

### ISSUE THREAD

**Issue by AronVanAmmers** [eris-ltd/hello-world-dapp#9]
Now that my setup with containers in a VM is working (#8) several tests pass but the one below fails. Which is a far minor issue, but I'm curious and of course would like the tests to pass.

I can reproduce it in a browser as well.

Node 1 on its own works fine:

1. Open http://localhost:3000/helloworld/
1. Add file "apple" with contents "apple!"
1. Alert "Added successfully"
1. Get file "apple"
1. Data shows "apple!"

Node 2 on its own works well too:

1. Open http://localhost:3001/helloworld/
1. Add file "pear" with contents "pear!"
1. Alert "Added successfully"
1. Get file "pear"
1. Data shows "pear!"

But getting the file from node 1 on node 2 gives the same result as the test script:

1. Open http://localhost:3001/helloworld/
1. Get file "apple"
1. Data shows "Path Resolve error: path must contain at least one component"

That message comes from ipfs; it seems node 2 doesn't have the hash for the file from node 1 in its contract, hence it's on another chain or a fork.

Output of `test.sh`:

```
2015/06/04 15:40:03 compiling remotely... http://compilers:9099/compile
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     7  100     7    0     0    214      0 --:--:-- --:--:-- --:--:--   218
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     7  100     7    0     0     52      0 --:--:-- --:--:-- --:--:--    53


Hello World Writer's DOUG Contract is at:
0x28acdd4b94e790111f2200e51f4329430431aa1a


> @ start /home/node
> nightwatch


[Hello World] Test Suite
========================

Running:  Hello World

✔  Element <//input[@id="filenameAdd"]> was visible after 114 milliseconds.
✔  Element <//div[@id="alertPresent"]> was present after 32 milliseconds.
✔  Element <//input[@id="filenameGet"]> was visible after 80 milliseconds.
✖  Testing if value of <//textarea[@id="output"]> equals: "Hello, world!".  - expected "Hello, world!" but got: Path Resolve error: path must contain at least one component


TEST FAILURE: 1 assertions failed, 3 passed and 1 skipped.. (19.91s)

npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.38
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE
npm ERR! @ start: `nightwatch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'nightwatch'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nightwatch
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/node/npm-debug.log
```

**Comment by AronVanAmmers** [comment]
Piped output of `test-debug.sh` here: 
https://gist.github.com/AronVanAmmers/d68483ce82a432729d3a

**Comment by compleatang** [comment]
OK. parsing the logs I'm noticing two things. 

When I search for `key_session` (to make sure all the nodes have different keys) I'm seeing a total of six nodes. It looks like each of the three main nodes is getting started twice. Although I'm not sure why they were each started twice, I think this is messing with Docker's behind the scenes DNS system which connects everything up. This leads me to the second item.

When you see in the logs either a `Peer Connect` or a `Block Mined` message (forget the wording exactly) you should see the other nodes soon thereafter respond (either with their own `Peer Connect` or `Unrequested Block` messages). Am not really sure why, but for some reason I don't see any interconnection like that in your logs. 

Are you just using the stock startup scripts or have you made your own?

**Comment by AronVanAmmers** [comment]
Using the stock startup scripts, just started `test-debug.sh` and later `test.sh`. As vanilla as possible :smile:

In an earlier attempt I adapted `test.sh` to add `sudo` everywhere but now I just use the unadapted version and start it with `sudo test.sh`.

**Comment by AronVanAmmers** [comment]
After running the install steps from a clean Ubuntu 14.04 VM, the issue was no longer reproducible.
